import Head from "next/head";
import { ReactElement } from "react";
import Header from "./Header";
import Footer from "./Footer";

type LayoutProps = Required<{
  readonly children: ReactElement;
}>;

const Layout = ({ children }: LayoutProps) => {
  return (
    <div>
      <Head>
        <title>Test Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
